### ISSUE TITLE
Fix up and down arrow icons missing on tip editor when editing questions that have sort order

### ISSUE THREAD

**Issue by markpfaff** [paulzwu/NSC-AD410-TIP-GROUP2#147]

**Comment by joseph-sayler** [comment]
did we determine this a css thing?

**Comment by markpfaff** [comment]
I don't know what originally caused it but I overwrote the styles and added new icons

**Comment by markpfaff** [comment]
It would be good to figure out what originally caused it because it will probably affect other things.

**Comment by markpfaff** [comment]
I'm going to close this and create a new issue for troubleshooting style conflicts
