### ISSUE TITLE
Create way for admins to select which tip assessment is automatically loaded for faculty

### ISSUE THREAD

**Issue by markpfaff** [paulzwu/NSC-AD410-TIP-GROUP2#160]
Instead of a load button on the tip page it should load the tip assessment the faculty choose

**Comment by joseph-sayler** [comment]
do we want this to be an interface for admins only that will allow them to assign a quiz to a user, or an interface for admins to select the current quiz to use for all users?

**Comment by markpfaff** [comment]
It should assign to all users. Assigning to individual users would be a
great extra feature but priority is assigning to all.

-- 
Mark Pfaff

From: Joseph Sayler <notifications@github.com> <notifications@github.com>
Reply: paulzwu/NSC-AD410-TIP-GROUP2
<reply@reply.github.com>
<reply@reply.github.com>
Date: June 3, 2017 at 2:48:22 PM
To: paulzwu/NSC-AD410-TIP-GROUP2 <nsc-ad410-tip-group2@noreply.github.com>
<nsc-ad410-tip-group2@noreply.github.com>
CC: Mark Pfaff <markdpfaff@gmail.com> <markdpfaff@gmail.com>, Assign
<assign@noreply.github.com> <assign@noreply.github.com>
Subject:  Re: [paulzwu/NSC-AD410-TIP-GROUP2] Create way for admins to
select which tip assessment is automatically loaded for faculty (#160)

do we want this to be an interface for admins only that will allow them to

**Comment by joseph-sayler** [comment]
making some headway on this. there will (eventually) be a button that the admin will click. it will show them which quiz in the db is the current default. then they click on whichever quiz they want to be the new default, and a flag in db will be set. that flag will be read by tip.php, and will load only that survey.

keep in mind, i have most of the first half done. the work has been uploaded to repo, check out my commit logs to see it.

**Comment by joseph-sayler** [comment]
this is done as of this issue being created. 

talked to @markpfaff about turning this into a function that allows the assignment of individual TIPs to individual users. will leave this issue open for discussion

**Comment by joseph-sayler** [comment]
alright, i finished some new functionality. i added logic to pull a users current answers if the tip is incomplete. later, i will add a quicksave function. then after that i will add the ability for admins to selectively assign tips to users (assuming there is enough time).

**Comment by joseph-sayler** [comment]
this is done. the quicksave is not part of this functionality and is implemented elsewhere
