### ISSUE TITLE
Add date/time stamp and set complete flag when user submits answers

### ISSUE THREAD

**Issue by joseph-sayler** [paulzwu/NSC-AD410-TIP-GROUP2#175]
we already went over this on slack but to recap: 

when user hits submit, json is saved to db. also want a time stamp set and the complete flag flipped.

**Comment by joseph-sayler** [comment]
have you uploaded this yet?

**Comment by nbekris** [comment]
Not yet, I will when I get home though. Still haven't figured out adding
answerID to the linking table. But I've tested what I've done so far and it
works so I'll upload that

**Comment by joseph-sayler** [comment]
this is done, closing
