### ISSUE TITLE
question templates in editor missing a menu

### ISSUE THREAD

**Issue by joseph-sayler** [paulzwu/NSC-AD410-TIP-GROUP2#177]
when a question template is picked and you click on the question in the editor, next to the edit button should be a symbol like this: . . .

this symbol opens a little menu that has a function to delete questions. is there any way you could look into finding out what happened to that menu?

**Comment by supreti17** [comment]
I tried clicking the area where the ... symbol is supposed to be and it shows the options. The icon is not there though for some reason.
![capture](https://user-images.githubusercontent.com/26189042/26999570-e14081de-4d51-11e7-820f-b9b3fbd94d74.PNG)

**Comment by markpfaff** [comment]
We were missing the glyphicon fonts, I've added them and added references in styles.css
